add an NPE check while getting Content-Type
soramitsu/dauth-springsecurity pull request #7
Opened 2019-05-29 14:32 UTC by JIexa

2019-05-29 14:38 UTC, rogachevsn55 requested changes

2019-05-29 14:38 UTC, rogachevsn55 commented on src/main/java/jp/co/soramitsu/sora/dauth/security/RequestReplacingFilter.java
> +    if (contentType.startsWith(MULTIPART_FORM_DATA_VALUE)) {
мы же обсуждали проверку на null чтобы NPE здесь не ловить

2019-05-29 15:00 UTC, JIexa commented on src/main/java/jp/co/soramitsu/sora/dauth/security/RequestReplacingFilter.java
> +    if (contentType.startsWith(MULTIPART_FORM_DATA_VALUE)) {
да, сорян, косяк

2019-05-30 07:18 UTC, rogachevsn55 approved these changes

2019-05-30 07:18 UTC, merged